apiVersion: v1
kind: Template
metadata:
  name: iperf3
  annotations:
    description: >-
      Iperf
    iconClass: "icon-sso"
    tags: "iperf"
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: iperf
    spec:
      dockerImageRepository: docker.io/scureq/iperf
  
  - kind: Service
    apiVersion: v1
    name: iperf
    metadata:
      labels:
        app: iperf
      name: iperf
    spec:
      ports:
        - name: 5201-tcp
          port: 5201
          protocol: TCP
          targetPort: 5201
      selector:
        deploymentconfig: iperf3
      sessionAffinity: None
      type: ClusterIP

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: iperf3
      name: iperf3
    spec:
      replicas: 1
      selector:
        app: iperf3
        deploymentconfig: iperf3
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: iperf3
            deploymentconfig: iperf3
        spec:
          containers:
          - image: docker.io/scureq/iperf
            imagePullPolicy: IfNotPresent
            name: iperf
            ports:
              - containerPort: 5201
                protocol: TCP
            resources:
              limits:
                memory: 1Gi
                #cpu: 1
              requests:
                memory: 0.5Gi
                cpu: 0.5
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
         - type: ImageChange
           imageChangeParams:
             automatic: true
             containerNames:
                - iperf
             from:
                kind: ImageStreamTag
                name: iperf:latest
         - type: ConfigChange
labels:
  template: iperf3