apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: openam
  name: openam
  namespace: am-dev
spec:
  replicas: 1
  selector:
    app: openam
    deploymentconfig: openam
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: openam
        deploymentconfig: openam
    spec:
      containers:
        - env:
            - name: HOME
              value: /usr/local/tomcat
          image:
            am-dev/openam-eval
          imagePullPolicy: IfNotPresent
          name: openam
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/local/tomcat/openam-configuration
              name: volume-openam
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: volume-openam
          persistentVolumeClaim:
            claimName: openam
  test: false
  triggers:
     - type: ImageChange
       imageChangeParams:
         automatic: true
         containerNames:
            - openam
         from:
            kind: ImageStreamTag
            name: openam-eval:latest
     - type: ConfigChange