apiVersion: v1
kind: Route
metadata:
  labels:
    app: openam
  name: openam
  namespace: am-dev
spec:
  path: /openam
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: openam
    weight: 100
  wildcardPolicy: None